const express = require("express");
const authMiddleware = require("../middleware/authMiddleware");
const { getMatches, createConnectionRequest, getProviderRequests, getRequesterRequests, updateRequestStatus } = require("../controllers/connectionController");
const router = express.Router();
router.get("/matches", authMiddleware, getMatches);
router.post("/request", authMiddleware, createConnectionRequest);
router.get("/requests/sent", authMiddleware, getRequesterRequests);
router.get("/requests/received", authMiddleware, getProviderRequests);
router.patch("/requests/:requestId/status", authMiddleware, updateRequestStatus);
module.exports = router;
